CREATE TABLE article_type (
    article_type_id INTEGER not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME TEXT not null UNIQUE
);

CREATE TABLE article (
    article_id BIGINT not null PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT not null,
    description TEXT not null,
    created_at timestamptz not null DEFAULT NOW(),
    overwrite_time timestamptz not null,
    article_type_id INTEGER not null REFERENCES article_type (article_type_id)
);